import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
const REQUIRED_BONE_HINTS=['hips','spine','head','leftarm','rightarm','leftleg','rightleg'];
const FACIAL_ALIASES={jawOpen:['jawopen','mouthopen','viseme_aa','aa'],smile:['mouthsmileleft','mouthsmileright','smile','happy'],blinkLeft:['eyeblinkleft','blink_left','blinkleft'],blinkRight:['eyeblinkright','blink_right','blinkright']};
const normalize=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
export class CharacterRuntime{
constructor({scene,onStatus=()=>{}}){this.scene=scene;this.onStatus=onStatus;this.root=null;this.mixer=null;this.actions=new Map();this.morphs=new Map();this.bones=new Map();this.ready=false}
async load(url){this.onStatus('Đang tải mesh + rig thật…');const gltf=await new GLTFLoader().loadAsync(url);this.root=gltf.scene;this.root.traverse(obj=>{obj.frustumCulled=false;if(obj.isMesh){obj.castShadow=true;obj.receiveShadow=true}if(obj.isBone)this.bones.set(normalize(obj.name),obj);if(obj.morphTargetDictionary){for(const [name,index] of Object.entries(obj.morphTargetDictionary))this.morphs.set(normalize(name),{mesh:obj,index,name})}});this._fitToStage();this.scene.add(this.root);this.mixer=new THREE.AnimationMixer(this.root);for(const clip of gltf.animations){const key=normalize(clip.name);this.actions.set(key,this.mixer.clipAction(clip))}this.ready=true;const report=this.inspect();this.onStatus(`Rigged GLB ✓ · ${report.bones} bones · ${report.morphTargets} morphs · ${report.clips} clips`);return report}
_fitToStage(){const box=new THREE.Box3().setFromObject(this.root);const size=box.getSize(new THREE.Vector3());const center=box.getCenter(new THREE.Vector3());const target=4.7;const scale=target/Math.max(size.y,.001);this.root.scale.setScalar(scale);this.root.position.set(-center.x*scale,-box.min.y*scale,-center.z*scale)}
inspect(){const names=[...this.bones.keys()];const missingBones=REQUIRED_BONE_HINTS.filter(h=>!names.some(n=>n.includes(h)));const facial={};for(const [role,aliases] of Object.entries(FACIAL_ALIASES))facial[role]=aliases.some(a=>this.morphs.has(normalize(a)));return {bones:this.bones.size,morphTargets:this.morphs.size,clips:this.actions.size,missingBones,facial}}
findAction(candidates=[]){for(const c of candidates){const key=normalize(c);for(const [name,a] of this.actions)if(name.includes(key))return a}return null}
play(candidates,{fade=.28,loop=THREE.LoopRepeat,clamp=false,timeScale=1}={}){if(!this.mixer)return false;const next=this.findAction(candidates);if(!next)return false;for(const a of this.actions.values())if(a!==next&&a.isRunning())a.fadeOut(fade);next.reset().setLoop(loop,loop===THREE.LoopOnce?1:Infinity);next.clampWhenFinished=clamp;next.timeScale=timeScale;next.fadeIn(fade).play();return true}
setMorph(role,value){const aliases=FACIAL_ALIASES[role]||[role];let hit=false;for(const alias of aliases){const entry=this.morphs.get(normalize(alias));if(entry){entry.mesh.morphTargetInfluences[entry.index]=THREE.MathUtils.clamp(value,0,1);hit=true}}return hit}
update(dt){this.mixer?.update(dt)} }
