import * as THREE from 'three';
import './styles.css';
import { CharacterRuntime } from './character-runtime.js';
import { MotionController } from './motion-controller.js';
import { LipSync } from './lip-sync.js';
const app=document.querySelector('#app');
app.innerHTML=`<main class="app" data-app-ready="false"><section class="stage" id="stage"><div class="poster" id="poster"><div><strong>Bác Gấu V11</strong><p>Runtime đã chuyển sang nhân vật GLB có rig thật. Poster chỉ xuất hiện khi asset 3D chưa được gắn vào build.</p></div></div><div class="pill">V11 · RIGGED CHARACTER</div><div class="loading" id="loading"><div><div class="spinner"></div><b>Đang khởi tạo Bác Gấu…</b></div></div><div class="caption" id="caption">Xin chào Muối! 👋</div></section><aside class="panel"><div class="brand"><div class="avatar">🐾</div><div><h1>Bác Gấu</h1><div class="sub">Người bạn đồng hành của Muối</div></div></div><div class="status"><span class="dot"></span><b id="status">Đang khởi tạo runtime…</b><div class="wave">${'<i></i>'.repeat(28)}</div></div><button data-state="welcoming">🏠 Muối về — vẫy tay</button><button data-state="gentle">🙂 Con buồn — cúi nghe</button><button data-state="thinking">🤔 Hỏi khó — suy nghĩ</button><button data-state="playful">🎲 Kể chuyện — hào hứng</button><button class="secondary" id="voiceTest">🔊 Test giọng + lip-sync</button><audio id="voice" preload="auto" playsinline src="https://bacgau-pass82-safari-full.vercel.app/api/asset?name=vi-test.mp3"></audio><div class="quality">QUALITY GATE: không procedural spheres/boxes · GLB skeleton · facial morph targets · animation mixer · audio-driven jaw · same artifact on Chrome/WebKit.</div><pre class="debug" id="debug">booting…</pre></aside></main>`;
for(const [i,e] of [...document.querySelectorAll('.wave i')].entries())e.style.setProperty('--h',`${8+(i*13%27)}px`);
const stage=document.querySelector('#stage'),loading=document.querySelector('#loading'),poster=document.querySelector('#poster'),status=document.querySelector('#status'),debug=document.querySelector('#debug'),caption=document.querySelector('#caption');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8bc8ed);scene.fog=new THREE.Fog(0x8bc8ed,10,28);const camera=new THREE.PerspectiveCamera(32,1,.1,100);camera.position.set(0,2.85,9.2);camera.lookAt(0,2.35,0);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;stage.prepend(renderer.domElement);scene.add(new THREE.HemisphereLight(0xfff0d8,0x28462f,2.1));const key=new THREE.DirectionalLight(0xffe3bd,4);key.position.set(-4,7,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const rim=new THREE.DirectionalLight(0x95caff,1.3);rim.position.set(5,4,-3);scene.add(rim);const floor=new THREE.Mesh(new THREE.CircleGeometry(6,64),new THREE.MeshStandardMaterial({color:0x7b522e,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
const character=new CharacterRuntime({scene,onStatus:t=>status.textContent=t});let motion=null;const lip=new LipSync(character);const voice=document.querySelector('#voice');lip.attach(voice);const MODEL_URL='/character/bac-gau.glb';
try{const report=await character.load(MODEL_URL);poster.hidden=true;motion=new MotionController(character,t=>caption.textContent=t);motion.setState('idle');debug.textContent=JSON.stringify(report,null,2);window.__BACGAU_V11__={ready:true,model:true,report};}catch(err){poster.hidden=false;status.textContent='V11 runtime ✓ · đang chờ rigged GLB';debug.textContent=`MODEL PENDING\n${err?.message||err}`;window.__BACGAU_V11__={ready:true,model:false,error:String(err)}}finally{loading.hidden=true;document.querySelector('.app').dataset.appReady='true'}
document.querySelectorAll('[data-state]').forEach(btn=>btn.onclick=()=>motion?.setState(btn.dataset.state));document.querySelector('#voiceTest').onclick=async()=>{voice.currentTime=0;await voice.play()};function resize(){const r=stage.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}resize();addEventListener('resize',resize);const clock=new THREE.Clock();function tick(){const dt=Math.min(.05,clock.getDelta());character.update(dt);motion?.update(dt);lip.update();renderer.render(scene,camera);requestAnimationFrame(tick)}tick();
