const B=window.BacGauBrain;let state=B.init();let active='listening';
const states={welcoming:{img:'assets/welcoming.jpg',label:'WELCOME',motion:'open'},listening:{img:'assets/listening.jpg',label:'LISTENING',motion:'listen'},thinking:{img:'assets/thinking.jpg',label:'THINKING',motion:'think'},gentle:{img:'assets/gentle.jpg',label:'GENTLE',motion:'gentle'},home:{img:'assets/home.jpg',label:'HOME',motion:'open'}};
const audioMap={home:'assets/home.mp3',listen:'assets/listen.mp3',sad:'assets/sad.mp3',think:'assets/think.mp3',english:'assets/english.mp3'};
const heroA=document.getElementById('heroA'),heroB=document.getElementById('heroB'),statusEl=document.getElementById('status'),bubble=document.getElementById('bubble'),audio=document.getElementById('voice'),pulse=document.getElementById('pulse'),eyes=document.getElementById('eyes'),world=document.getElementById('world');
let front=heroA,back=heroB,blinkTimer;
function perform(name){const c=states[name]||states.listening; active=name; back.src=c.img; back.onload=()=>{back.className='hero front state-'+c.motion;front.className='hero back'; const t=front;front=back;back=t};statusEl.textContent=c.label+' · '+(document.documentElement.lang==='en'?'en-US':'vi-VN');document.body.dataset.performance=c.motion;scheduleBlink();}
function scheduleBlink(){clearTimeout(blinkTimer);eyes.classList.remove('blink');const delay=2200+Math.random()*4200;blinkTimer=setTimeout(()=>{eyes.classList.add('blink');setTimeout(()=>eyes.classList.remove('blink'),160);scheduleBlink()},delay)}
function speak(key){const src=audioMap[key]||audioMap.listen;audio.pause();audio.src=src;audio.load();audio.onplay=()=>{pulse.classList.add('speaking');document.body.classList.add('speaking')};audio.onended=()=>{pulse.classList.remove('speaking');document.body.classList.remove('speaking')};audio.play().catch(()=>{})}
function apply(result,withAudio=true){state=result.stateData;document.documentElement.lang=result.language.startsWith('en')?'en':'vi';bubble.textContent=result.speech;perform(result.performance);world.textContent='emotion '+result.emotion+' · next '+result.next+(result.safety!=='ok'?' · safety '+result.safety:'');if(withAudio)speak(result.audio)}
function react(text){apply(B.decide(text,state),true)}
window.__bacgau={react,brain:B,getState:()=>state,getActive:()=>active};document.querySelectorAll('[data-say]').forEach(b=>b.onclick=()=>react(b.dataset.say));
const input=document.getElementById('input'),send=document.getElementById('send');send.onclick=()=>{const t=input.value.trim();if(t){input.value='';react(t)}};input.addEventListener('keydown',e=>{if(e.key==='Enter')send.click()});perform('listening');scheduleBlink();
