const B=window.BacGauBrain;const L=window.BacGauLiveness;let state=B.init();let active='listening';let lastPlan=null;
const states={welcoming:{img:'assets/welcoming.jpg',label:'WELCOME',motion:'open'},listening:{img:'assets/listening.jpg',label:'LISTENING',motion:'listen'},thinking:{img:'assets/thinking.jpg',label:'THINKING',motion:'think'},gentle:{img:'assets/gentle.jpg',label:'GENTLE',motion:'gentle'},playful:{img:'assets/home.jpg',label:'PLAYFUL',motion:'playful'},home:{img:'assets/home.jpg',label:'HOME',motion:'open'}};
const audioMap={home:{src:'assets/home.mp3',lang:'vi-VN'},listen:{src:'assets/listen.mp3',lang:'vi-VN'},sad:{src:'assets/sad.mp3',lang:'vi-VN'},think:{src:'assets/think.mp3',lang:'vi-VN'},english:{src:'assets/english.mp3',lang:'en-US'}};
const heroA=document.getElementById('heroA'),heroB=document.getElementById('heroB'),statusEl=document.getElementById('status'),bubble=document.getElementById('bubble'),audio=document.getElementById('voice'),pulse=document.getElementById('pulse'),eyes=document.getElementById('eyes'),world=document.getElementById('world');
let front=heroA,back=heroB,blinkTimer,microTimer;
function applyPlan(plan){lastPlan=plan;document.body.dataset.performance=plan.performance;document.body.dataset.gaze=plan.gaze;document.body.dataset.head=plan.head;document.body.dataset.brow=plan.brow;document.body.dataset.mouth=plan.mouth;document.body.dataset.gesture=plan.gesture;document.documentElement.style.setProperty('--breath-scale',String(plan.breathScale));document.documentElement.style.setProperty('--micro-shift-ms',plan.microShiftMs+'ms');document.documentElement.style.setProperty('--eye-open',String(plan.eyeOpen??.9));document.documentElement.style.setProperty('--brow-lift',String(plan.browLift??0));document.documentElement.style.setProperty('--jaw-open',String(plan.jawOpen??.02));document.documentElement.style.setProperty('--speech-energy',String(plan.speechEnergy??.3));scheduleBlink(plan.blinkMs);clearTimeout(microTimer);microTimer=setTimeout(()=>{document.body.classList.toggle('micro-shift')},plan.microShiftMs)}
function perform(name,text=''){const c=states[name]||states.listening;active=name;back.src=c.img;back.onload=()=>{back.className='hero front state-'+c.motion;front.className='hero back';const t=front;front=back;back=t};statusEl.textContent=c.label+' · '+(document.documentElement.lang==='en'?'en-US':'vi-VN');const plan=L?L.plan({performance:name==='home'?'welcoming':name,turn:state.turn||0,text,previous:lastPlan,speaking:false}):{performance:name,blinkMs:3200,breathScale:.8,microShiftMs:1600,gaze:'child',head:'neutral',brow:'neutral',mouth:'rest',gesture:'micro-nod',eyeOpen:.9,browLift:0,jawOpen:.02,speechEnergy:.3};applyPlan(plan)}
function scheduleBlink(delay){clearTimeout(blinkTimer);eyes.classList.remove('blink');const d=Math.max(1200,Number(delay)||3200);blinkTimer=setTimeout(()=>{eyes.classList.add('blink');setTimeout(()=>eyes.classList.remove('blink'),160);scheduleBlink(d+Math.round(Math.random()*1200-600))},d)}
function stopSpeechForInterrupt(kind='normal'){audio.pause();audio.currentTime=0;pulse.classList.remove('speaking');document.body.classList.remove('speaking');if(L&&lastPlan){const next=L.onInterrupt(lastPlan,{kind});perform(next.nextPerformance)}}
function speak(key,language){const clip=audioMap[key]||audioMap.listen;const expected=(language||'vi-VN').startsWith('en')?'en-US':'vi-VN';if(clip.lang!==expected){world.textContent='VOICE BLOCKED · locale mismatch '+clip.lang+' ≠ '+expected;return false}audio.pause();audio.src=clip.src;audio.dataset.expectedLang=clip.lang;audio.load();audio.onplay=()=>{pulse.classList.add('speaking');document.body.classList.add('speaking');if(L&&lastPlan)applyPlan(L.plan({performance:lastPlan.performance,turn:state.turn||0,text:bubble.textContent,previous:lastPlan,speaking:true}))};audio.onended=()=>{pulse.classList.remove('speaking');document.body.classList.remove('speaking');if(L&&lastPlan)applyPlan(L.plan({performance:lastPlan.performance,turn:state.turn||0,text:bubble.textContent,previous:lastPlan,speaking:false}))};audio.play().catch(()=>{});return true}
function apply(result,withAudio=true){state=result.stateData;document.documentElement.lang=result.language.startsWith('en')?'en':'vi';bubble.textContent=result.speech;perform(result.performance,result.speech);world.textContent='emotion '+result.emotion+' · next '+result.next+(result.safety!=='ok'?' · safety '+result.safety:'');if(withAudio)speak(result.audio,result.language)}
function react(text){if(document.body.classList.contains('speaking'))stopSpeechForInterrupt(/buồn|khóc|sad|hurt|die|tự tử|muốn chết/i.test(text)?'distress':'normal');apply(B.decide(text,state),true)}
window.__bacgau={react,brain:B,liveness:L,getState:()=>state,getActive:()=>active,getPlan:()=>lastPlan,interrupt:stopSpeechForInterrupt};document.querySelectorAll('[data-say]').forEach(b=>b.onclick=()=>react(b.dataset.say));
const input=document.getElementById('input'),send=document.getElementById('send');send.onclick=()=>{const t=input.value.trim();if(t){input.value='';react(t)}};input.addEventListener('keydown',e=>{if(e.key==='Enter')send.click()});perform('listening');
