(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports) module.exports=api;
  root.BacGauLiveness=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const STATES={
    welcoming:{gaze:'child',blink:[2000,4500],breath:.88,head:'open',brow:'lift-soft',mouth:'smile-soft',gesture:['small-wave','open-palm'],latency:[120,380],interrupt:[180,320],chunk:[900,1500],event:'normal',face:{eyeOpen:.86,browLift:.21,innerBrow:.09,jawRest:.035,speechEnergy:.68,smile:.34,cheek:.20,muzzle:.10,squint:.085},pose:{lean:.082,headTilt:-.035,neckLean:.032,shoulder:.095,shoulderAsym:.045,armOpen:.48,pawCurl:.09,gazeX:0,gazeY:-.010,eyeContact:.90}},
    listening:{gaze:'child-soft',blink:[2500,5500],breath:.73,head:'micro-nod',brow:'neutral-soft',mouth:'rest',gesture:['micro-nod','ear-tilt'],latency:[80,240],interrupt:[80,180],chunk:[600,1100],event:'normal',face:{eyeOpen:.80,browLift:.035,innerBrow:.03,jawRest:.012,speechEnergy:.32,smile:.055,cheek:.04,muzzle:.02,squint:.095},pose:{lean:.035,headTilt:.025,neckLean:.016,shoulder:.018,shoulderAsym:.016,armOpen:.08,pawCurl:.15,gazeX:0,gazeY:-.020,eyeContact:.96}},
    thinking:{gaze:'up-side',blink:[2900,5900],breath:.63,head:'tilt',brow:'pinch-soft',mouth:'ponder',gesture:['chin-think','small-pause'],latency:[450,1100],interrupt:[120,240],chunk:[700,1200],event:'quiet',face:{eyeOpen:.67,browLift:-.065,innerBrow:.145,jawRest:.025,speechEnergy:.38,smile:-.025,cheek:.012,muzzle:-.04,squint:.18},pose:{lean:-.028,headTilt:.112,neckLean:.055,shoulder:-.025,shoulderAsym:.065,armOpen:.025,pawCurl:.22,gazeX:.16,gazeY:.09,eyeContact:.42}},
    gentle:{gaze:'child-steady',blink:[3300,6600],breath:.56,head:'lower-soft',brow:'inner-up',mouth:'soft-closed',gesture:['slow-nod','hand-heart'],latency:[260,700],interrupt:[70,150],chunk:[500,900],event:'suppress-nonessential',face:{eyeOpen:.69,browLift:.13,innerBrow:.24,jawRest:.008,speechEnergy:.24,smile:.02,cheek:.025,muzzle:.008,squint:.19},pose:{lean:.078,headTilt:-.06,neckLean:.047,shoulder:-.08,shoulderAsym:.014,armOpen:.12,pawCurl:.20,gazeX:0,gazeY:-.052,eyeContact:.99}},
    playful:{gaze:'child-bright',blink:[1800,3900],breath:.96,head:'tilt-bounce',brow:'asym-lift',mouth:'smirk',gesture:['peek','tiny-shrug'],latency:[100,320],interrupt:[120,220],chunk:[700,1100],event:'normal',face:{eyeOpen:.88,browLift:.29,innerBrow:.065,jawRest:.045,speechEnergy:.80,smile:.45,cheek:.28,muzzle:.14,squint:.075},pose:{lean:.105,headTilt:.13,neckLean:.067,shoulder:.13,shoulderAsym:.105,armOpen:.54,pawCurl:.065,gazeX:-.045,gazeY:.025,eyeContact:.83}}
  };
  function hash(s=''){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
  function pick(arr,seed){return arr[seed%arr.length]}
  function range(pair,seed){return pair[0]+(seed%(pair[1]-pair[0]+1))}
  function clamp(n,min=0,max=1){return Math.max(min,Math.min(max,n))}
  function plan({performance='listening',turn=0,text='',previous=null,speaking=false}={}){
    const key=STATES[performance]?performance:'listening',cfg=STATES[key],seed=hash(`${turn}|${text}|${key}`);
    let gesture=pick(cfg.gesture,seed);if(previous&&gesture===previous.gesture&&cfg.gesture.length>1)gesture=cfg.gesture[(cfg.gesture.indexOf(gesture)+1)%cfg.gesture.length];
    const syllablePulse=.78+((seed>>>20)%17)/100,asym=(((seed>>>5)%21)-10)/1000,faceAsym=(((seed>>>9)%17)-8)/1000;
    const arcOn=range([100,230],seed>>>2),arcHold=range([380,900],seed>>>9),arcOff=range([200,540],seed>>>13);
    const emotionAsym=key==='playful'?.12:key==='thinking'?.045:key==='gentle'?.018:key==='welcoming'?.025:0;
    const p={performance:key,gaze:cfg.gaze,blinkMs:range(cfg.blink,seed),breathScale:cfg.breath,head:cfg.head,brow:cfg.brow,mouth:cfg.mouth,gesture,responseDelayMs:range(cfg.latency,seed>>>8),microShiftMs:1000+((seed>>>16)%1900),interruptWindowMs:range(cfg.interrupt,seed>>>4),speechChunkMs:range(cfg.chunk,seed>>>12),eventPolicy:cfg.event,resumePolicy:key==='gentle'?'ask-before-resume':'resume-if-context-valid',speaking:!!speaking,idleAlive:true,eyeOpen:cfg.face.eyeOpen,browLift:cfg.face.browLift,browInnerLift:cfg.face.innerBrow,browAsym:emotionAsym+faceAsym,jawOpen:cfg.face.jawRest,jawSide:faceAsym*.35,speechEnergy:cfg.face.speechEnergy,smile:cfg.face.smile,smileAsym:(key==='playful'?.055:key==='welcoming'?.025:0)+faceAsym*.8,cheekLift:cfg.face.cheek,cheekAsym:(key==='playful'?.035:0)+faceAsym*.7,muzzleLift:cfg.face.muzzle,muzzleCompress:key==='gentle'?.045:key==='thinking'?.025:0,eyeSquint:cfg.face.squint,torsoLean:cfg.pose.lean,headTilt:cfg.pose.headTilt,neckLean:cfg.pose.neckLean,shoulderSet:cfg.pose.shoulder,shoulderAsym:cfg.pose.shoulderAsym+asym,armOpenness:cfg.pose.armOpen,pawCurl:cfg.pose.pawCurl,gazeX:cfg.pose.gazeX+asym,gazeY:cfg.pose.gazeY,eyeContactRatio:cfg.pose.eyeContact,anticipationMs:range([100,250],seed>>>6),blinkAsymMs:range([24,88],seed>>>10),microSaccadeMs:range([820,2200],seed>>>14),weightShiftMs:range([2800,5800],seed>>>18),gazeHoldMs:range([650,1650],seed>>>3),transitionMs:range([240,500],seed>>>7),audioEnvelopeAttackMs:range([30,64],seed>>>11),audioEnvelopeReleaseMs:range([100,190],seed>>>15),visemeLagMs:range([36,80],seed>>>19),preSpeechBreath:key==='gentle'?.026:key==='playful'?.075:.05,headLeadMs:range([90,200],seed>>>4),gestureLeadMs:range([110,280],seed>>>12),settleMs:range([320,760],seed>>>16),doubleBlinkChance:key==='playful'?.13:key==='gentle'?.035:.065,motionNoise:key==='gentle'?.012:key==='thinking'?.018:key==='playful'?.042:.024,emotionArc:{onsetMs:arcOn,holdMs:arcHold,releaseMs:arcOff,peak:key==='gentle'?.66:key==='thinking'?.72:key==='listening'?.58:.88}};
    if(speaking){p.gaze=key==='thinking'?'child-soft':p.gaze;p.mouth='speech-animated';p.jawOpen=clamp(cfg.face.jawRest+cfg.face.speechEnergy*syllablePulse*.52,.07,.56);p.eyeOpen=clamp(cfg.face.eyeOpen-cfg.face.speechEnergy*.035,.58,.91);p.torsoLean+=.014;p.anticipatory=true;p.eyeContactRatio=clamp(p.eyeContactRatio-(key==='thinking'?.09:.015),.35,1);p.smile=clamp(p.smile+((key==='welcoming'||key==='playful')?.025:0),-.15,.52);}else p.anticipatory=false;
    return p;
  }
  function onInterrupt(plan,event={}){const danger=event.kind==='safety'||event.kind==='distress';return {stopSpeech:true,acknowledgeWithinMs:Math.min(plan.interruptWindowMs||180,danger?100:220),audioFadeOutMs:danger?35:65,mouthSettleMs:danger?70:110,reacquireGazeWithinMs:danger?120:180,nextPerformance:danger?'gentle':'listening',discardQueuedGesture:true,preserveTopic:event.topic!==false,resumePolicy:danger?'do-not-auto-resume':plan.resumePolicy||'resume-if-context-valid'};}
  function deadCharacterAudit(plans){const issues=[];if(!plans.length)return ['no-plans'];for(const f of ['gaze','head','brow','mouth','gesture'])if(new Set(plans.map(p=>p[f])).size<2)issues.push(`static-${f}`);for(const f of ['eyeOpen','browLift','browInnerLift','headTilt','torsoLean','smile','eyeContactRatio','armOpenness','eyeSquint'])if(new Set(plans.map(p=>Number(p[f]).toFixed(2))).size<3)issues.push(`static-${f}`);if(!plans.some(p=>p.speaking&&p.jawOpen>.07))issues.push('dead-jaw');if(plans.some(p=>!p.blinkMs||!p.microShiftMs||!p.microSaccadeMs||!p.weightShiftMs||!p.blinkAsymMs||!p.interruptWindowMs||!p.speechChunkMs||!p.gazeHoldMs||!p.transitionMs||!p.audioEnvelopeAttackMs||!p.audioEnvelopeReleaseMs||!p.visemeLagMs||!p.headLeadMs||!p.gestureLeadMs||!p.settleMs||!p.emotionArc||!p.idleAlive))issues.push('missing-micro-motion');if(plans.some(p=>p.eyeOpen<0||p.eyeOpen>1||p.jawOpen<0||p.jawOpen>1||p.speechEnergy<0||p.speechEnergy>1||p.eyeContactRatio<0||p.eyeContactRatio>1||p.armOpenness<0||p.armOpenness>1||p.cheekLift<0||p.cheekLift>1||p.eyeSquint<0||p.eyeSquint>.25||p.pawCurl<0||p.pawCurl>1))issues.push('face-range-invalid');for(let i=1;i<plans.length;i++)if(plans[i].gesture===plans[i-1].gesture)issues.push('repeated-gesture');if(plans.some(p=>p.performance==='gentle'&&p.eventPolicy!=='suppress-nonessential'))issues.push('gentle-event-leak');if(plans.some(p=>p.speaking&&!p.anticipatory))issues.push('missing-speech-anticipation');if(plans.some(p=>p.speaking&&(p.visemeLagMs<20||p.audioEnvelopeAttackMs>=p.audioEnvelopeReleaseMs)))issues.push('speech-envelope-invalid');if(plans.some(p=>p.emotionArc.onsetMs>=p.emotionArc.holdMs||p.emotionArc.releaseMs<120||p.emotionArc.peak<.5))issues.push('emotion-arc-invalid');if(plans.some(p=>p.eyeOpen>.92||p.eyeSquint<.04))issues.push('uncanny-eye-aperture');return [...new Set(issues)];}
  return {STATES,plan,onInterrupt,deadCharacterAudit};
});

// Live presentation pass: keep the warm/cool hierarchy while improving facial separation.
// This is intentionally restrained; the fixed screenshot gate remains the authority.
if(typeof document!=='undefined')queueMicrotask(()=>{
  const stage=document.getElementById('stage'); if(!stage)return;
  const tuneCanvas=()=>{const c=stage.querySelector('canvas');if(!c)return false;c.style.filter='contrast(1.12) saturate(1.075) brightness(1.03)';return true};
  if(!tuneCanvas()){const mo=new MutationObserver(()=>{if(tuneCanvas())mo.disconnect()});mo.observe(stage,{childList:true})}
  for(const n of stage.querySelectorAll('.cinematic-depth-pass,.cinematic-grade-pass,.character-light-pass'))n.remove();
  const d=document.createElement('div');d.className='cinematic-grade-pass';
  Object.assign(d.style,{position:'absolute',inset:'0',zIndex:'2',pointerEvents:'none',borderRadius:'inherit',
    background:'radial-gradient(ellipse at 31% 30%, rgba(255,215,176,.115) 0%, rgba(255,191,136,.042) 24%, transparent 48%), radial-gradient(ellipse at 80% 28%, rgba(111,166,215,.11) 0%, rgba(67,113,158,.035) 30%, transparent 56%), radial-gradient(ellipse at 48% 86%, rgba(218,111,61,.085) 0%, transparent 39%), linear-gradient(90deg, rgba(16,8,5,.105) 0%, transparent 18% 76%, rgba(7,14,23,.115) 100%)',
    boxShadow:'inset 0 0 138px rgba(3,2,2,.30), inset 0 -92px 116px rgba(12,6,4,.18), inset 0 72px 108px rgba(255,218,180,.03)',mixBlendMode:'soft-light',opacity:'.96'});
  stage.appendChild(d);
});
