(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports) module.exports=api;
  root.BacGauLiveness=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const STATES={
    welcoming:{gaze:'child',blink:[1800,4200],breath:.90,head:'open',brow:'lift-soft',mouth:'smile-soft',gesture:['small-wave','open-palm'],latency:[120,380],interrupt:[180,320],chunk:[900,1500],event:'normal',face:{eyeOpen:.96,browLift:.22,jawRest:.05,speechEnergy:.72,smile:.34,cheek:.20,muzzle:.12},pose:{lean:.08,headTilt:-.03,shoulder:.10,shoulderAsym:.04,armOpen:.42,gazeX:0,gazeY:0,eyeContact:.88}},
    listening:{gaze:'child-soft',blink:[2200,5200],breath:.75,head:'micro-nod',brow:'neutral-soft',mouth:'rest',gesture:['micro-nod','ear-tilt'],latency:[80,240],interrupt:[80,180],chunk:[600,1100],event:'normal',face:{eyeOpen:.90,browLift:.05,jawRest:.015,speechEnergy:.34,smile:.08,cheek:.06,muzzle:.03},pose:{lean:.045,headTilt:.035,shoulder:.03,shoulderAsym:.02,armOpen:.12,gazeX:0,gazeY:-.015,eyeContact:.94}},
    thinking:{gaze:'up-side',blink:[2600,5600],breath:.65,head:'tilt',brow:'pinch-soft',mouth:'ponder',gesture:['chin-think','small-pause'],latency:[450,1100],interrupt:[120,240],chunk:[700,1200],event:'quiet',face:{eyeOpen:.76,browLift:-.08,jawRest:.03,speechEnergy:.40,smile:-.03,cheek:.01,muzzle:-.05},pose:{lean:-.02,headTilt:.10,shoulder:-.02,shoulderAsym:.06,armOpen:.04,gazeX:.16,gazeY:.10,eyeContact:.42}},
    gentle:{gaze:'child-steady',blink:[3000,6200],breath:.58,head:'lower-soft',brow:'inner-up',mouth:'soft-closed',gesture:['slow-nod','hand-heart'],latency:[260,700],interrupt:[70,150],chunk:[500,900],event:'suppress-nonessential',face:{eyeOpen:.82,browLift:.16,jawRest:.01,speechEnergy:.26,smile:.04,cheek:.04,muzzle:.02},pose:{lean:.075,headTilt:-.045,shoulder:-.07,shoulderAsym:.015,armOpen:.18,gazeX:0,gazeY:-.045,eyeContact:.97}},
    playful:{gaze:'child-bright',blink:[1500,3600],breath:1,head:'tilt-bounce',brow:'asym-lift',mouth:'smirk',gesture:['peek','tiny-shrug'],latency:[100,320],interrupt:[120,220],chunk:[700,1100],event:'normal',face:{eyeOpen:1,browLift:.28,jawRest:.06,speechEnergy:.86,smile:.46,cheek:.28,muzzle:.16},pose:{lean:.10,headTilt:.12,shoulder:.14,shoulderAsym:.09,armOpen:.50,gazeX:-.035,gazeY:.025,eyeContact:.83}}
  };
  function hash(s=''){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
  function pick(arr,seed){return arr[seed%arr.length]}
  function range(pair,seed){return pair[0]+(seed%(pair[1]-pair[0]+1))}
  function clamp(n,min=0,max=1){return Math.max(min,Math.min(max,n))}
  function plan({performance='listening',turn=0,text='',previous=null,speaking=false}={}){
    const key=STATES[performance]?performance:'listening',cfg=STATES[key],seed=hash(`${turn}|${text}|${key}`);
    let gesture=pick(cfg.gesture,seed);if(previous&&gesture===previous.gesture&&cfg.gesture.length>1)gesture=cfg.gesture[(cfg.gesture.indexOf(gesture)+1)%cfg.gesture.length];
    const syllablePulse=.78+((seed>>>20)%17)/100,asym=(((seed>>>5)%21)-10)/1000;
    const arcOn=range([90,220],seed>>>2),arcHold=range([360,880],seed>>>9),arcOff=range([180,520],seed>>>13);
    const p={performance:key,gaze:cfg.gaze,blinkMs:range(cfg.blink,seed),breathScale:cfg.breath,head:cfg.head,brow:cfg.brow,mouth:cfg.mouth,gesture,responseDelayMs:range(cfg.latency,seed>>>8),microShiftMs:900+((seed>>>16)%1800),interruptWindowMs:range(cfg.interrupt,seed>>>4),speechChunkMs:range(cfg.chunk,seed>>>12),eventPolicy:cfg.event,resumePolicy:key==='gentle'?'ask-before-resume':'resume-if-context-valid',speaking:!!speaking,idleAlive:true,eyeOpen:cfg.face.eyeOpen,browLift:cfg.face.browLift,browAsym:key==='playful'?.13+asym:asym,jawOpen:cfg.face.jawRest,speechEnergy:cfg.face.speechEnergy,smile:cfg.face.smile,cheekLift:cfg.face.cheek,muzzleLift:cfg.face.muzzle,torsoLean:cfg.pose.lean,headTilt:cfg.pose.headTilt,shoulderSet:cfg.pose.shoulder,shoulderAsym:cfg.pose.shoulderAsym+asym,armOpenness:cfg.pose.armOpen,gazeX:cfg.pose.gazeX+asym,gazeY:cfg.pose.gazeY,eyeContactRatio:cfg.pose.eyeContact,anticipationMs:range([90,240],seed>>>6),blinkAsymMs:range([18,74],seed>>>10),microSaccadeMs:range([650,1900],seed>>>14),weightShiftMs:range([2400,5200],seed>>>18),gazeHoldMs:range([520,1450],seed>>>3),transitionMs:range([180,420],seed>>>7),audioEnvelopeAttackMs:range([28,62],seed>>>11),audioEnvelopeReleaseMs:range([90,180],seed>>>15),visemeLagMs:range([34,78],seed>>>19),preSpeechBreath:key==='gentle'?.035:key==='playful'?.085:.055,headLeadMs:range([70,180],seed>>>4),gestureLeadMs:range([90,260],seed>>>12),settleMs:range([260,680],seed>>>16),doubleBlinkChance:key==='playful'?.18:key==='gentle'?.05:.09,motionNoise:key==='gentle'?.018:key==='playful'?.055:.032,emotionArc:{onsetMs:arcOn,holdMs:arcHold,releaseMs:arcOff,peak:key==='gentle'?.72:key==='thinking'?.78:.90}};
    if(speaking){p.gaze=key==='thinking'?'child-soft':p.gaze;p.mouth='speech-animated';p.jawOpen=clamp(cfg.face.jawRest+cfg.face.speechEnergy*syllablePulse*.58,.08,.62);p.eyeOpen=clamp(cfg.face.eyeOpen-cfg.face.speechEnergy*.035,.62,1);p.torsoLean+=.018;p.anticipatory=true;p.eyeContactRatio=clamp(p.eyeContactRatio-(key==='thinking'?.10:.02),.30,1);p.smile=clamp(p.smile+((key==='welcoming'||key==='playful')?.04:0),-.2,.6);}else p.anticipatory=false;
    return p;
  }
  function onInterrupt(plan,event={}){const danger=event.kind==='safety'||event.kind==='distress';return {stopSpeech:true,acknowledgeWithinMs:Math.min(plan.interruptWindowMs||180,danger?100:220),audioFadeOutMs:danger?35:65,mouthSettleMs:danger?70:110,reacquireGazeWithinMs:danger?120:180,nextPerformance:danger?'gentle':'listening',discardQueuedGesture:true,preserveTopic:event.topic!==false,resumePolicy:danger?'do-not-auto-resume':plan.resumePolicy||'resume-if-context-valid'};}
  function deadCharacterAudit(plans){const issues=[];if(!plans.length)return ['no-plans'];for(const f of ['gaze','head','brow','mouth','gesture'])if(new Set(plans.map(p=>p[f])).size<2)issues.push(`static-${f}`);if(new Set(plans.map(p=>p.responseDelayMs)).size<3)issues.push('robotic-timing');if(new Set(plans.map(p=>p.eyeOpen.toFixed(2))).size<3)issues.push('static-eyelids');if(new Set(plans.map(p=>p.browLift.toFixed(2))).size<3)issues.push('static-brows');if(new Set(plans.map(p=>p.headTilt.toFixed(2))).size<3)issues.push('static-head-tilt');if(new Set(plans.map(p=>p.torsoLean.toFixed(2))).size<3)issues.push('static-body-lean');if(new Set(plans.map(p=>p.smile.toFixed(2))).size<3)issues.push('static-smile');if(new Set(plans.map(p=>p.eyeContactRatio.toFixed(2))).size<3)issues.push('static-eye-contact');if(new Set(plans.map(p=>p.armOpenness.toFixed(2))).size<3)issues.push('static-arm-openness');if(!plans.some(p=>p.speaking&&p.jawOpen>.08))issues.push('dead-jaw');if(plans.some(p=>!p.blinkMs||!p.microShiftMs||!p.microSaccadeMs||!p.weightShiftMs||!p.blinkAsymMs||!p.interruptWindowMs||!p.speechChunkMs||!p.gazeHoldMs||!p.transitionMs||!p.audioEnvelopeAttackMs||!p.audioEnvelopeReleaseMs||!p.visemeLagMs||!p.headLeadMs||!p.gestureLeadMs||!p.settleMs||!p.emotionArc||!p.idleAlive))issues.push('missing-micro-motion');if(plans.some(p=>p.eyeOpen<0||p.eyeOpen>1||p.jawOpen<0||p.jawOpen>1||p.speechEnergy<0||p.speechEnergy>1||p.eyeContactRatio<0||p.eyeContactRatio>1||p.armOpenness<0||p.armOpenness>1||p.cheekLift<0||p.cheekLift>1))issues.push('face-range-invalid');for(let i=1;i<plans.length;i++)if(plans[i].gesture===plans[i-1].gesture)issues.push('repeated-gesture');if(plans.some(p=>p.performance==='gentle'&&p.eventPolicy!=='suppress-nonessential'))issues.push('gentle-event-leak');if(plans.some(p=>p.speaking&&!p.anticipatory))issues.push('missing-speech-anticipation');if(plans.some(p=>p.speaking&&(p.visemeLagMs<20||p.audioEnvelopeAttackMs>=p.audioEnvelopeReleaseMs)))issues.push('speech-envelope-invalid');if(plans.some(p=>p.emotionArc.onsetMs>=p.emotionArc.holdMs||p.emotionArc.releaseMs<120||p.emotionArc.peak<.5))issues.push('emotion-arc-invalid');return [...new Set(issues)];}
  return {STATES,plan,onInterrupt,deadCharacterAudit};
});
