(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports) module.exports=api;
  root.BacGauLiveness=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const STATES={
    welcoming:{gaze:'child',blink:[1900,4400],breath:.88,head:'open',brow:'lift-soft',mouth:'smile-soft',gesture:['small-wave','open-palm'],latency:[120,380],interrupt:[180,320],chunk:[900,1500],event:'normal',face:{eyeOpen:.89,browLift:.18,innerBrow:.08,jawRest:.035,speechEnergy:.68,smile:.29,cheek:.16,muzzle:.09,squint:.07},pose:{lean:.07,headTilt:-.025,neckLean:.025,shoulder:.08,shoulderAsym:.035,armOpen:.38,pawCurl:.10,gazeX:0,gazeY:-.008,eyeContact:.89}},
    listening:{gaze:'child-soft',blink:[2400,5400],breath:.73,head:'micro-nod',brow:'neutral-soft',mouth:'rest',gesture:['micro-nod','ear-tilt'],latency:[80,240],interrupt:[80,180],chunk:[600,1100],event:'normal',face:{eyeOpen:.83,browLift:.04,innerBrow:.025,jawRest:.012,speechEnergy:.32,smile:.07,cheek:.045,muzzle:.025,squint:.085},pose:{lean:.04,headTilt:.03,neckLean:.018,shoulder:.025,shoulderAsym:.018,armOpen:.10,pawCurl:.14,gazeX:0,gazeY:-.018,eyeContact:.95}},
    thinking:{gaze:'up-side',blink:[2800,5800],breath:.63,head:'tilt',brow:'pinch-soft',mouth:'ponder',gesture:['chin-think','small-pause'],latency:[450,1100],interrupt:[120,240],chunk:[700,1200],event:'quiet',face:{eyeOpen:.70,browLift:-.055,innerBrow:.10,jawRest:.025,speechEnergy:.38,smile:-.015,cheek:.015,muzzle:-.035,squint:.16},pose:{lean:-.018,headTilt:.085,neckLean:.045,shoulder:-.015,shoulderAsym:.05,armOpen:.045,pawCurl:.20,gazeX:.13,gazeY:.075,eyeContact:.48}},
    gentle:{gaze:'child-steady',blink:[3200,6400],breath:.56,head:'lower-soft',brow:'inner-up',mouth:'soft-closed',gesture:['slow-nod','hand-heart'],latency:[260,700],interrupt:[70,150],chunk:[500,900],event:'suppress-nonessential',face:{eyeOpen:.75,browLift:.12,innerBrow:.19,jawRest:.008,speechEnergy:.24,smile:.035,cheek:.03,muzzle:.012,squint:.145},pose:{lean:.068,headTilt:-.038,neckLean:.038,shoulder:-.055,shoulderAsym:.012,armOpen:.16,pawCurl:.18,gazeX:0,gazeY:-.04,eyeContact:.98}},
    playful:{gaze:'child-bright',blink:[1700,3800],breath:.96,head:'tilt-bounce',brow:'asym-lift',mouth:'smirk',gesture:['peek','tiny-shrug'],latency:[100,320],interrupt:[120,220],chunk:[700,1100],event:'normal',face:{eyeOpen:.91,browLift:.23,innerBrow:.06,jawRest:.045,speechEnergy:.80,smile:.39,cheek:.23,muzzle:.12,squint:.055},pose:{lean:.085,headTilt:.10,neckLean:.055,shoulder:.11,shoulderAsym:.075,armOpen:.44,pawCurl:.08,gazeX:-.03,gazeY:.018,eyeContact:.85}}
  };
  function hash(s=''){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
  function pick(arr,seed){return arr[seed%arr.length]}
  function range(pair,seed){return pair[0]+(seed%(pair[1]-pair[0]+1))}
  function clamp(n,min=0,max=1){return Math.max(min,Math.min(max,n))}
  function plan({performance='listening',turn=0,text='',previous=null,speaking=false}={}){
    const key=STATES[performance]?performance:'listening',cfg=STATES[key],seed=hash(`${turn}|${text}|${key}`);
    let gesture=pick(cfg.gesture,seed);if(previous&&gesture===previous.gesture&&cfg.gesture.length>1)gesture=cfg.gesture[(cfg.gesture.indexOf(gesture)+1)%cfg.gesture.length];
    const syllablePulse=.78+((seed>>>20)%17)/100,asym=(((seed>>>5)%21)-10)/1000,faceAsym=(((seed>>>9)%17)-8)/1000;
    const arcOn=range([100,230],seed>>>2),arcHold=range([380,900],seed>>>9),arcOff=range([200,540],seed>>>13);
    const p={performance:key,gaze:cfg.gaze,blinkMs:range(cfg.blink,seed),breathScale:cfg.breath,head:cfg.head,brow:cfg.brow,mouth:cfg.mouth,gesture,responseDelayMs:range(cfg.latency,seed>>>8),microShiftMs:1000+((seed>>>16)%1900),interruptWindowMs:range(cfg.interrupt,seed>>>4),speechChunkMs:range(cfg.chunk,seed>>>12),eventPolicy:cfg.event,resumePolicy:key==='gentle'?'ask-before-resume':'resume-if-context-valid',speaking:!!speaking,idleAlive:true,eyeOpen:cfg.face.eyeOpen,browLift:cfg.face.browLift,browInnerLift:cfg.face.innerBrow,browAsym:(key==='playful'?.105:0)+faceAsym,jawOpen:cfg.face.jawRest,jawSide:faceAsym*.35,speechEnergy:cfg.face.speechEnergy,smile:cfg.face.smile,smileAsym:faceAsym*.8,cheekLift:cfg.face.cheek,cheekAsym:faceAsym*.7,muzzleLift:cfg.face.muzzle,muzzleCompress:key==='gentle'?.035:key==='thinking'?.018:0,eyeSquint:cfg.face.squint,torsoLean:cfg.pose.lean,headTilt:cfg.pose.headTilt,neckLean:cfg.pose.neckLean,shoulderSet:cfg.pose.shoulder,shoulderAsym:cfg.pose.shoulderAsym+asym,armOpenness:cfg.pose.armOpen,pawCurl:cfg.pose.pawCurl,gazeX:cfg.pose.gazeX+asym,gazeY:cfg.pose.gazeY,eyeContactRatio:cfg.pose.eyeContact,anticipationMs:range([100,250],seed>>>6),blinkAsymMs:range([22,82],seed>>>10),microSaccadeMs:range([760,2100],seed>>>14),weightShiftMs:range([2700,5600],seed>>>18),gazeHoldMs:range([600,1550],seed>>>3),transitionMs:range([210,460],seed>>>7),audioEnvelopeAttackMs:range([30,64],seed>>>11),audioEnvelopeReleaseMs:range([100,190],seed>>>15),visemeLagMs:range([36,80],seed>>>19),preSpeechBreath:key==='gentle'?.03:key==='playful'?.075:.05,headLeadMs:range([80,190],seed>>>4),gestureLeadMs:range([100,270],seed>>>12),settleMs:range([300,720],seed>>>16),doubleBlinkChance:key==='playful'?.15:key==='gentle'?.04:.075,motionNoise:key==='gentle'?.014:key==='playful'?.045:.027,emotionArc:{onsetMs:arcOn,holdMs:arcHold,releaseMs:arcOff,peak:key==='gentle'?.68:key==='thinking'?.74:.86}};
    if(speaking){p.gaze=key==='thinking'?'child-soft':p.gaze;p.mouth='speech-animated';p.jawOpen=clamp(cfg.face.jawRest+cfg.face.speechEnergy*syllablePulse*.52,.07,.56);p.eyeOpen=clamp(cfg.face.eyeOpen-cfg.face.speechEnergy*.03,.60,.94);p.torsoLean+=.014;p.anticipatory=true;p.eyeContactRatio=clamp(p.eyeContactRatio-(key==='thinking'?.08:.015),.35,1);p.smile=clamp(p.smile+((key==='welcoming'||key==='playful')?.03:0),-.15,.52);}else p.anticipatory=false;
    return p;
  }
  function onInterrupt(plan,event={}){const danger=event.kind==='safety'||event.kind==='distress';return {stopSpeech:true,acknowledgeWithinMs:Math.min(plan.interruptWindowMs||180,danger?100:220),audioFadeOutMs:danger?35:65,mouthSettleMs:danger?70:110,reacquireGazeWithinMs:danger?120:180,nextPerformance:danger?'gentle':'listening',discardQueuedGesture:true,preserveTopic:event.topic!==false,resumePolicy:danger?'do-not-auto-resume':plan.resumePolicy||'resume-if-context-valid'};}
  function deadCharacterAudit(plans){const issues=[];if(!plans.length)return ['no-plans'];for(const f of ['gaze','head','brow','mouth','gesture'])if(new Set(plans.map(p=>p[f])).size<2)issues.push(`static-${f}`);for(const f of ['eyeOpen','browLift','browInnerLift','headTilt','torsoLean','smile','eyeContactRatio','armOpenness','eyeSquint'])if(new Set(plans.map(p=>Number(p[f]).toFixed(2))).size<3)issues.push(`static-${f}`);if(!plans.some(p=>p.speaking&&p.jawOpen>.07))issues.push('dead-jaw');if(plans.some(p=>!p.blinkMs||!p.microShiftMs||!p.microSaccadeMs||!p.weightShiftMs||!p.blinkAsymMs||!p.interruptWindowMs||!p.speechChunkMs||!p.gazeHoldMs||!p.transitionMs||!p.audioEnvelopeAttackMs||!p.audioEnvelopeReleaseMs||!p.visemeLagMs||!p.headLeadMs||!p.gestureLeadMs||!p.settleMs||!p.emotionArc||!p.idleAlive))issues.push('missing-micro-motion');if(plans.some(p=>p.eyeOpen<0||p.eyeOpen>1||p.jawOpen<0||p.jawOpen>1||p.speechEnergy<0||p.speechEnergy>1||p.eyeContactRatio<0||p.eyeContactRatio>1||p.armOpenness<0||p.armOpenness>1||p.cheekLift<0||p.cheekLift>1||p.eyeSquint<0||p.eyeSquint>.25||p.pawCurl<0||p.pawCurl>1))issues.push('face-range-invalid');for(let i=1;i<plans.length;i++)if(plans[i].gesture===plans[i-1].gesture)issues.push('repeated-gesture');if(plans.some(p=>p.performance==='gentle'&&p.eventPolicy!=='suppress-nonessential'))issues.push('gentle-event-leak');if(plans.some(p=>p.speaking&&!p.anticipatory))issues.push('missing-speech-anticipation');if(plans.some(p=>p.speaking&&(p.visemeLagMs<20||p.audioEnvelopeAttackMs>=p.audioEnvelopeReleaseMs)))issues.push('speech-envelope-invalid');if(plans.some(p=>p.emotionArc.onsetMs>=p.emotionArc.holdMs||p.emotionArc.releaseMs<120||p.emotionArc.peak<.5))issues.push('emotion-arc-invalid');if(plans.some(p=>p.eyeOpen>.95||p.eyeSquint<0))issues.push('uncanny-eye-aperture');return [...new Set(issues)];}
  return {STATES,plan,onInterrupt,deadCharacterAudit};
});

// Live presentation pass: preserve the last verified green warm/cool hierarchy while
// keeping the newer, softer eye-performance plan above. Do not weaken screenshot gates.
if(typeof document!=='undefined')queueMicrotask(()=>{
  const stage=document.getElementById('stage'); if(!stage)return;
  const tuneCanvas=()=>{const c=stage.querySelector('canvas');if(!c)return false;c.style.filter='contrast(1.115) saturate(1.085) brightness(1.025)';return true};
  if(!tuneCanvas()){const mo=new MutationObserver(()=>{if(tuneCanvas())mo.disconnect()});mo.observe(stage,{childList:true})}
  for(const n of stage.querySelectorAll('.cinematic-depth-pass,.cinematic-grade-pass,.character-light-pass'))n.remove();
  const d=document.createElement('div');d.className='cinematic-grade-pass';
  Object.assign(d.style,{position:'absolute',inset:'0',zIndex:'2',pointerEvents:'none',borderRadius:'inherit',
    background:'radial-gradient(ellipse at 31% 31%, rgba(255,210,167,.10) 0%, rgba(255,190,132,.035) 23%, transparent 47%), radial-gradient(ellipse at 80% 29%, rgba(105,164,215,.105) 0%, rgba(64,112,158,.032) 30%, transparent 55%), radial-gradient(ellipse at 50% 88%, rgba(211,103,54,.08) 0%, transparent 38%), linear-gradient(90deg, rgba(16,8,5,.10) 0%, transparent 18% 77%, rgba(7,14,23,.11) 100%)',
    boxShadow:'inset 0 0 145px rgba(3,2,2,.32), inset 0 -95px 120px rgba(12,6,4,.20), inset 0 70px 105px rgba(255,215,176,.025)',mixBlendMode:'soft-light',opacity:'.98'});
  stage.appendChild(d);
});
