const BASE='https://bacgau-character-v11-pass4.vercel.app/api/body';
const PATCHES=[
  ["const M=(c,r=.92)=>new THREE.MeshPhysicalMaterial({color:c,roughness:r,metalness:0,sheen:.18,sheenRoughness:.84,sheenColor:new THREE.Color(c).offsetHSL(0,0,.05),clearcoat:.015,clearcoatRoughness:.9})","const M=(c,r=.92)=>new THREE.MeshPhysicalMaterial({color:c,roughness:r,metalness:0,sheen:.24,sheenRoughness:.76,sheenColor:new THREE.Color(c).offsetHSL(0,0,.045),clearcoat:.006,clearcoatRoughness:.96})"],
  ["scene.add(new THREE.HemisphereLight(0xffead8,0x2b2425,1.14));const key=new THREE.DirectionalLight(0xffd2ad,2.18);","scene.add(new THREE.HemisphereLight(0xffead8,0x2b2425,1.02));const key=new THREE.DirectionalLight(0xffd2ad,1.82);"],
  ["const fill=new THREE.PointLight(0xffb574,3.05,10,2);","const fill=new THREE.PointLight(0xffb574,2.38,10,2);"],
  ["const faceFill=new THREE.PointLight(0xffd7bc,1.25,6,2);","const faceFill=new THREE.PointLight(0xffd7bc,.92,6,2);"],
  ["renderer.toneMappingExposure=1.02;","renderer.toneMappingExposure=1.04;"],
  ["const nose=S(.132,.082,.074,dark,.68);nose.position.set(0,-.11,.92);headRig.add(nose);","const nose=S(.132,.082,.074,dark,.68);nose.material=new THREE.MeshPhysicalMaterial({color:dark,roughness:.34,metalness:0,clearcoat:.20,clearcoatRoughness:.46,sheen:.04});nose.position.set(0,-.11,.92);headRig.add(nose);"],
  ["const white=S(.116,.091,.046,scl,.72);white.castShadow=false;sclera.add(white);","const white=S(.116,.091,.046,scl,.72);white.material=new THREE.MeshPhysicalMaterial({color:0xe2d6ca,roughness:.33,metalness:0,clearcoat:.18,clearcoatRoughness:.40});white.castShadow=false;sclera.add(white);"],
  ["const ir=S(.094,.086,.030,iris,.52);ir.castShadow=false;look.add(ir);","const ir=S(.094,.086,.030,iris,.52);ir.material=new THREE.MeshPhysicalMaterial({color:iris,roughness:.27,metalness:0,clearcoat:.32,clearcoatRoughness:.30});ir.castShadow=false;look.add(ir);"],
  ["const pu=S(.046,.052,.017,pupil,.36);pu.position.z=.027;pu.castShadow=false;look.add(pu);","const pu=S(.046,.052,.017,pupil,.36);pu.material=new THREE.MeshPhysicalMaterial({color:pupil,roughness:.20,metalness:0,clearcoat:.42,clearcoatRoughness:.24});pu.position.z=.027;pu.castShadow=false;look.add(pu);"],
  ["visualVersion:'v11-character-pass4'","visualVersion:'v11-character-pass5'"]
];
module.exports=async function handler(req,res){try{const r=await fetch(BASE,{headers:{'User-Agent':'bacgau-character-v11-pass5'}});if(!r.ok)return res.status(502).send('pass4 fetch failed');let html=await r.text();let applied=0;const missing=[];for(const [from,to] of PATCHES){if(html.includes(from)){html=html.split(from).join(to);applied++;}else missing.push(from.slice(0,90));}html=html.replace('content="v11-character-pass4"','content="v11-character-pass5"');html=html.replace('Character refinement · pass 4','Character refinement · pass 5');html=html.replace('</body>',`<script>window.__BACGAU_CHARACTER_PASS5__={version:'v11-character-pass5',applied:${applied},expected:${PATCHES.length},missing:${JSON.stringify(missing)}};<\/script></body>`);res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store');res.setHeader('X-BacGau-Character','v11-character-pass5');res.setHeader('X-BacGau-Pass5',`${applied}/${PATCHES.length}`);return res.status(200).send(html)}catch(e){return res.status(500).send('pass5 error: '+e.message)}};