const BASES=['https://bacgau-character-v11-pass5-j4zlrqa4j.vercel.app/api/body','https://bacgau-character-v11-pass5.vercel.app/api/body'];
const PATCHES=[
  ["renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));","const DPR=Math.min(devicePixelRatio||1,(innerWidth<700?1.35:1.8));renderer.setPixelRatio(DPR);"],
  ["async function play(k){viAudio.pause();enAudio.pause();scenarioAudio.pause();scenarioAudio.src=aud[k];scenarioAudio.currentTime=0;speaking=true;apply(k);await scenarioAudio.play();window.__BACGAU_SCENARIO_AUDIO__={state:k,src:scenarioAudio.currentSrc||scenarioAudio.src,played:true}}","async function play(k){viAudio.pause();enAudio.pause();scenarioAudio.pause();scenarioAudio.removeAttribute('src');scenarioAudio.load();speaking=false;apply(k);window.__BACGAU_SCENARIO_AUDIO__={state:k,src:null,played:false,reviewMode:true}}"],
  ["visualVersion:'v11-character-pass5'","visualVersion:'v11-character-pass6'"]
];
async function loadBase(){let last='';for(const url of BASES){for(let i=0;i<2;i++){try{const r=await fetch(url,{headers:{'User-Agent':'bacgau-character-v11-pass6','Cache-Control':'no-cache'}});if(r.ok)return await r.text();last=`${url} -> ${r.status}`;}catch(e){last=`${url} -> ${e.message}`;}await new Promise(resolve=>setTimeout(resolve,180));}}throw new Error(last||'pass5 unavailable');}
module.exports=async function handler(req,res){try{let html=await loadBase();let applied=0;const missing=[];for(const [from,to] of PATCHES){if(html.includes(from)){html=html.split(from).join(to);applied++;}else missing.push(from.slice(0,90));}
const harness=`<style id="reviewHarnessStyle">#reviewHarness{position:fixed;z-index:50;left:50%;bottom:max(14px,env(safe-area-inset-bottom));transform:translateX(-50%);display:flex;gap:8px;padding:8px;background:#17110db8;border:1px solid #ffffff20;border-radius:999px;backdrop-filter:blur(14px)}#reviewHarness button{width:auto!important;margin:0!important;padding:10px 12px!important;border-radius:999px!important;font-size:14px!important;white-space:nowrap}.bubble{bottom:86px!important}@media(max-width:560px){#reviewHarness{gap:5px;padding:6px;max-width:calc(100vw - 12px)}#reviewHarness button{padding:9px 9px!important;font-size:12px!important}.badge{display:none!important}.bubble{bottom:76px!important}}</style><div id="reviewHarness"><button data-review="welcoming">🏠 Vui</button><button data-review="gentle">😔 Dịu</button><button data-review="thinking">🤔 Nghĩ</button><button data-review="playful">🦖 Tinh nghịch</button></div><script>document.querySelectorAll('#reviewHarness [data-review]').forEach(btn=>btn.addEventListener('click',()=>{const k=btn.dataset.review;const target=document.querySelector('[data-state="'+k+'"]');if(target)target.click();}));window.addEventListener('error',e=>{const b=document.querySelector('.bubble');if(b&&/WebGL|context|shader/i.test(String(e.message||'')))b.textContent='Thiết bị chưa khởi tạo được 3D. Đang dùng chế độ an toàn.';});window.__BACGAU_REVIEW_MODE__={characterOnly:true,audioMuted:true,mobileDprCap:true};<\/script>`;
html=html.replace('</body>',harness+`<script>window.__BACGAU_CHARACTER_PASS6__={version:'v11-character-pass6',applied:${applied},expected:${PATCHES.length},missing:${JSON.stringify(missing)}};<\/script></body>`);html=html.replace('content="v11-character-pass5"','content="v11-character-pass6"');html=html.replace('Character refinement · pass 5','Character refinement · pass 6');res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store');res.setHeader('X-BacGau-Character','v11-character-pass6');res.setHeader('X-BacGau-Pass6',`${applied}/${PATCHES.length}`);return res.status(200).send(html)}catch(e){return res.status(502).send('pass6 base error: '+e.message)}};